VA-019:Save the audio in MongoDB
USB-VirtualAssistant/virtualAssistant pull request #13
Opened 2023-08-02 12:20 UTC by J-Ivan-MC

2023-08-03 00:08 UTC, zamoranoalicia requested changes

2023-08-03 00:08 UTC, zamoranoalicia commented on docker-compose.yml
> +      MONGO_INITDB_ROOT_PASSWORD: rGYwVKko8ihLmyaC
same here

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +    @Autowired
please dont use @Autowire here

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +    @Autowired
Spring injects the dependencies automatically

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +        Query query = new Query(Criteria.where("idRecording").is(idRecording));
You are repiting this same portion of code, in almost all of the methods, so please abstract this Query creating in a separated method

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +        Query query = new Query(Criteria.where("idRecording").is(idRecording));
same here, please apply DRY principle https://www.baeldung.com/cs/dry-software-design-principle

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +        if (recordingToDelete != null) {
invert this comparison, or use ofNullable(recordingToDelete).ifPresent()

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +            Document audioDocument = new Document("audio", encodedAudio);
use constant here for "audio"

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/repository/mongo/RecordingRepositoryImpl.java
> +            throw new RuntimeException(e + " Exception: Error in generate Document");
use especific exception here

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/java/org/fundacionjala/virtualassistant/services/mongo/RecordingService.java
> +
In this case is not necessary to create an interface for the service

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/resources/application.properties
> +spring.data.mongodb.username=VirtualAssistant60089
dont expose users and passwords

2023-08-03 00:08 UTC, zamoranoalicia commented on src/main/resources/application.properties
> +spring.data.mongodb.password=rGYwVKko8ihLmyaC
set this values as environment variables

2023-08-03 00:08 UTC, zamoranoalicia commented on src/test/java/org/fundacionjala/virtualassistant/services/mongo/RecordingServiceImplTest.java
> +import static org.mockito.Mockito.*;
dont use wildcards when importing classes use specific class names

2023-08-04 20:27 UTC, santihsdev commented
![](https://github.trello.services/images/mini-trello-icon.png) [VA-019 [SP-5]: Save the audio in MongoDB](https://trello.com/c/WkH55tcU/35-va-019-sp-5-save-the-audio-in-mongodb)

2023-08-09 16:37 UTC, merged